"""Constants for textract_extractor Lambda."""

import os

TEXTRACT_SNS_TOPIC_ARN = os.environ.get("TEXTRACT_SNS_TOPIC_ARN", "")
TEXTRACT_ROLE_ARN = os.environ.get("TEXTRACT_ROLE_ARN", "")
DYNAMODB_TABLE_NAME = os.environ.get("DYNAMODB_TABLE_NAME","")
OUTPUT_BUCKET = os.environ.get("OUTPUT_BUCKET","")
EXTRACTED_TEXT_PREFIX = os.environ.get("EXTRACTED_TEXT_PREFIX", "extracted/")

TEXTRACT_MAX_RESULTS = 1000

JOB_STATUS_SUBMITTED = "SUBMITTED"
JOB_STATUS_COMPLETED = "COMPLETED"
JOB_STATUS_FAILED = "FAILED"
